export const products = [
    {
        "id": 1,
        "productCounter":0,
        "productImg": 'https://cdn.x-kom.pl/i/setup/images/prod/big/product-new-big,,2019/9/pr_2019_9_11_9_8_51_565_00.jpg',
        "productName": "Smartphone",
        "productPrice": 1200,
        "productDescription": "Top Xiaomi smartphone",
    },
    {
        "id": 2,
        "productCounter":0,
        "productImg": "https://thumbs.img-sprzedajemy.pl/1000x901c/55/f4/f6/telefon-philips-xenium-e106-czarny-krakow-544963787.jpg",
        "productName": "Smartphone",
        "productPrice": 760,
        "productDescription": "Strongest smartphone",
    },
    {
        "id": 3,
        "productCounter":0,
        "productImg": "https://static.pepper.pl/live_pl/info-block/info_block_comparison_table/default/12875465081611305717.jpg",
        "productName": "Smartphone",
        "productPrice": 550,
        "productDescription": "Long hours on battery",
    },
    {
        "id": 4,
        "productCounter":0,
        "productImg": "https://a.allegroimg.com/s512/11d213/a02001ed403383b6c96148a30248/TELEFON-XIAOMI-MI-REDMi-NOTE-10-CZARNY-6-64GB",
        "productName": "Smartphone",
        "productPrice": 1500,
        "productDescription": "Good price, nice performance",
    },
    {
        "id": 5,
        "productCounter":0,
        "productImg": "https://images.morele.net/i1064/4716156_6_i1064.jpg",
        "productName": "Monitor",
        "productPrice": 400,
        "productDescription": "TN,60Hz,1920x1080",
    },
    {
        "id": 6,
        "productCounter":0,
        "productImg": 'https://cdn.x-kom.pl/i/setup/images/prod/big/product-new-big,,2018/7/pr_2018_7_24_23_26_55_525_01.jpg',
        "productName": "Monitor",
        "productPrice": 1300,
        "productDescription": "VA,75Hz,1920x1080",
    },
    {
        "id": 7,
        "productCounter":0,
        "productImg": "https://cdn.x-kom.pl/i/setup/images/prod/big/product-new-big,,2020/9/pr_2020_9_7_14_31_57_187_02.jpg",
        "productName": "Monitor",
        "productPrice": 1550,
        "productDescription": "IPS,144Hz,2560x1440,",
    },
    {
        "id": 8,
        "productCounter":0,
        "productImg": "https://sklep.hard-pc.pl/galerie/m/monitor-msi-optix-g24c4-24-14_37794.jpg",
        "productName": "Monitor",
        "productPrice": 1200,
        "productDescription": "IPS,120Hz,2560x1440",
    },
    {
        "id": 9,
        "productCounter":1,
        "productImg": "https://www.xiaomi4you.pl/wp-content/uploads/2020/10/IMG_20201029_152554-600x588.jpg",
        "productName": "Smartwatch",
        "productPrice": 860,
        "productDescription": "Great battery",
    },
    {
        "id": 10,
        "productCounter":0,
        "productImg": "https://topgadget.pl/wp-content/uploads/2019/05/metalowy-smartwatch-sportowy-z-kamera-600x629.jpg",
        "productName": "Smartwatch",
        "productPrice": 777,
        "productDescription": "Excellent display",
    },
    {
        "id": 11,
        "productCounter":0,
        "productImg": "https://majana.pl/aar_pl_Smartwatch-L8-inteligentny-zegarek-czarno-czerwony-615_1.jpg",
        "productName": "Smartwatch",
        "productPrice": 123,
        "productDescription": "Cheap,shows time",
    },
    {
        "id": 12,
        "productCounter":0,
        "productImg": "https://images-na.ssl-images-amazon.com/images/I/617v3mrXJnL._AC_SL1500_.jpg",
        "productName": "Smartwatch",
        "productPrice": 220,
        "productDescription": "Shows time and weather",
    },
    {
        "id": 13,
        "productCounter":0,
        "productImg": "https://image.ceneostatic.pl/data/products/37767979/183d21f8-5b8a-48a9-ada5-fe9170ce6b78_i-lg-105uc9.jpg",
        "productName": "TV",
        "productPrice": 560,
        "productDescription": "Great with netflix",
    },
    {
        "id": 14,
        "productCounter":0,
        "productImg": "https://cdn.benchmark.pl/uploads/backend_img/c/newsy/2020-10/WK/oppo-tv-r1-telewizor.jpg",
        "productName": "TV",
        "productPrice": 440,
        "productDescription": "Light and bright",
    },
    {
        "id": 15,
        "productCounter":0,
        "productImg": "https://www.electro.pl/media/cache/gallery/product/1/253/335/314/fugtqq0j/images/24/2402520/Telewizor-PHILIPS-LED-50PUS7555-skos.jpg",
        "productName": "TV",
        "productPrice": 3000,
        "productDescription": "Good price, nice performance",
    },
    {
        "id": 16,
        "productCounter":0,
        "productImg": "https://mi-store.pl/pol_pl_Telewizor-HD-Xiaomi-Mi-TV-4A-32-740_3.jpg",
        "productName": "TV",
        "productPrice": 3200,
        "productDescription": "Remote control",
    }
];
